name: Build and Upload Artifact

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame

    - name: Build application
      run: pyinstaller --onefile main.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: dist/main
